name: Deploy Docs

on:
  workflow_dispatch:
    inputs:
      product:
        required: true
        type: string
      version:
        required: true
        type: string
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: clone docs
      uses: actions/checkout@main
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: docs-files

    - name: clone frontend
      uses: actions/checkout@main
      with:
        repository: 'emqx/docs-emqx-com-frontend'
        ref: next
        token: ${{ secrets.CI_GIT_TOKEN }}
        path: frontend

    - name: use python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: install python dependencies
      run: |
        pip3 install requests

    - name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: 'frontend/.nvmrc'

    - name: use pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: set env
      run: |
        echo "DOCS_BRANCH=${{ inputs.ref }}" >> $GITHUB_ENV
        echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "DOCS_TYPE=${{ inputs.product }}" >> $GITHUB_ENV

    - name: remove unused files
      run: |
        cd docs-files
        python3 .github/scripts/remove_unused.py $(pwd)/docs

    - name: move files
      run: |
        rm frontend/docs/en/index.md || true
        rm frontend/docs/zh/index.md || true
        rm frontend/docs/*.md || true
        rm frontend/index.md || true
        mkdir -p frontend/docs/en/${DOCS_TYPE}/${VERSION}/
        mkdir -p frontend/docs/zh/${DOCS_TYPE}/${VERSION}/
        mkdir -p frontend/docs/public/api/
        cp -r docs-files/docs/en_US/* frontend/docs/en/${DOCS_TYPE}/${VERSION}/
        cp -r docs-files/docs/zh_CN/* frontend/docs/zh/${DOCS_TYPE}/${VERSION}/
        cp docs-files/docs/directory.json frontend/docs/.vitepress/config/directory.json

    - name: build docs
      run: |
        cd frontend
        pnpm install
        pnpm build

    - name: set aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: upload dist to s3
      run: |
        aws s3 rm --recursive s3://docs-emqx-com/zh/${DOCS_TYPE}/${VERSION} || true
        aws s3 rm --recursive s3://docs-emqx-com/en/${DOCS_TYPE}/${VERSION} || true
        aws s3 cp --recursive frontend/docs/.vitepress/dist/ s3://docs-emqx-com/
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DOCS_CLOUDFRONT_ID }} --paths "/zh/${DOCS_TYPE}/${VERSION}/*" "/en/${DOCS_TYPE}/${VERSION}/*" "/api/${DOCS_TYPE}_versions.json" "/sitemap_${DOCS_TYPE}_${VERSION}.xml"

    - name: upload dist to cos
      run: |
        pip3 install coscmd
        coscmd config -a ${{ secrets.TENCENT_COS_ID }} -s ${{ secrets.TENCENT_COS_KEY }} -b docs-1302406139 -r ap-shanghai
        coscmd delete -r -f en/${DOCS_TYPE}/${VERSION} || true
        coscmd delete -r -f zh/${DOCS_TYPE}/${VERSION} || true
        coscmd config -a ${{ secrets.TENCENT_COS_ID }} -s ${{ secrets.TENCENT_COS_KEY }} -b docs-1302406139 -e cos.accelerate.myqcloud.com
        coscmd upload -r frontend/docs/.vitepress/dist/ /

    - name: flush cdn
      run: |
        pip3 install tccli
        tccli configure set secretId ${{ secrets.TENCENT_COS_ID }}
        tccli configure set secretKey ${{ secrets.TENCENT_COS_KEY }}
        tccli configure set region ap-shanghai
        tccli cdn PurgePathCache --cli-unfold-argument --Paths https://docs.emqx.com/zh/${DOCS_TYPE}/${VERSION}/ https://docs.emqx.com/en/${DOCS_TYPE}/${VERSION}/ --FlushType delete
        tccli cdn PurgeUrlsCache --cli-unfold-argument --Urls https://docs.emqx.com/api/${DOCS_TYPE}_versions.json https://docs.emqx.com/sitemap_${DOCS_TYPE}_${VERSION}.xml

    - name: update search index
      uses: Swilder-M/docsearch-scraper-simple@next
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID_NEXT }}
        API_KEY: ${{ secrets.ALGOLIA_API_KEY_NEXT }}
      with:
        docs_type: ${{ env.DOCS_TYPE }}
        docs_version: ${{ env.VERSION }}
