name: Update Search Index

on:
  workflow_dispatch:
    inputs:
      product:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - name: update search index
      uses: Swilder-M/docsearch-scraper-simple@next
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID_NEXT }}
        API_KEY: ${{ secrets.ALGOLIA_API_KEY_NEXT }}
      with:
        docs_type: ${{ inputs.product }}
        docs_version: ${{ inputs.version }}
